#!/bin/bash

watch_conf="/data/etc/watch.conf"
netwatch_retries=3
netwatch_timeout=5
netwatch_interval=20

test -f $watch_conf && source $watch_conf || exit 0

if [ -z "$netwatch_host" ] || [ -z "$netwatch_port" ]; then
    exit 0
fi

watch() {
    count=0
    netwatch_retries=$(($netwatch_retries - 1))
    while true; do
        sleep $netwatch_interval

        haveInternet=true
        case "$(curl -s --max-time 2 -I $netwatch_host | sed 's/^[^ ]*  *\([0-9]\).*/\1/; 1q')" in
          [23]) haveInternet=true;;
          5) haveInternet=true;;
          *) haveInternet=false;;
        esac

        if [ "$haveInternet" = "true" ] ; then
            count=0
        else
            if [ $count -lt $netwatch_retries ]; then
                logger -t netwatch -s "cannot connect to $netwatch_host"
                count=$(($count + 1))
                continue
            else
                logger -t netwatch -s "cannot connect to $netwatch_host, rebooting"
                reboot
            fi
        fi
    done
}

case "$1" in
    start)
        msg_begin "Starting netwatch"
        if [ "$netwatch_enable" == "yes" ]; then
          watch &
        fi
        msg_done
        ;;

    stop)
        msg_begin "Stopping netwatch"
        ps | grep netwatch | grep -v $$ | grep -v grep | tr -s ' ' | sed -e 's/^\s//' | cut -d ' ' -f 1 | xargs -r kill
        msg_done
        ;;

    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
