#!/bin/bash

start() {
    /usr/bin/memcached -u root &
}

stop() {
    killall memcached &>/dev/null
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?