#!/bin/bash

sys_conf="/etc/opt/kerberosio/config/config.xml"
conf="/data/machinery/config/config.xml"

if [ -f $sys_conf ] && ! [ -f $conf ]; then
    mkdir -p /data/machinery/config
    cp -R /etc/opt/kerberosio/config/* /data/machinery/config/
    mkdir -p /data/machinery/symbols
    mkdir -p /data/machinery/logs
    mkdir -p /data/machinery/capture
fi

start() {
    msg_begin "Starting kerberos.io machinery"
    kerberosio $conf &
    msg_done
}

stop() {
    msg_begin "Stopping kerberos.io machinery"
    ps | grep kerberosio | grep -v $$ | grep -v grep | tr -s ' ' | sed -e 's/^\s//' | cut -d ' ' -f 1 | xargs -r kill
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
