#!/bin/bash

sys_conf="/var/www/web"
conf="/data/www/"

start() {
    echo "Configuring kerberos.io web"
    
    if [ -d $sys_conf ] && ! [ -d $conf ]; then
        mkdir -p /data/www/cache
        mkdir -p /data/www/logs
        mkdir -p /data/www/meta
        mkdir -p /data/www/sessions
        mkdir -p /data/www/views
        chmod -R 777 /data/www
    fi
}

stop() {

}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
