#!/bin/bash

sys_conf="/var/www/web"
conf="/data/web/app"

start() {
    echo "Configuring kerberos.io web"
    
    if [ -d $sys_conf ] && ! [ -d $conf ]; then
        mkdir -p /data/web/app
        cp -R /var/www/web/app/storage /data/web/app
        cp -R /var/www/web/app/config /data/web/app
        sed -i "s#__DIR__.'/../views'#'/var/www/web/app/views'#g" /data/web/app/config/view.php
        chmod -R 777 /data/web/app
    fi
}

stop() {
    echo "Stopping kerberos.io web"
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
