#!/bin/sh
#
# Start/stop nginx
#

PIDFILE=/var/run/nginx.pid
PROG="/usr/sbin/nginx"

case "$1" in
  start)
	echo "Starting nginx..."
	mkdir -p /var/log/nginx /var/tmp/nginx
	${PROG}
	;;
  stop)
	echo -n "Stopping nginx..."
	killall -q $(basename ${PROG})
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
